### ISSUE TITLE
V0.9.7 'class BitsAndDroidsFlightConnector' has no member named 'sendFlaps1'  error

### ISSUE THREAD

**Issue by simtcrom** [BitsAndDroids/Bits-and-Droids-flight-connector#11]
I am following https://www.youtube.com/watch?v=OLUch71k7Yg&list=PLmpPdxFqn9_SsYlp0sbKWLF40t0Saaj1z&index=1
Installed library v0.9.7
And wrote below code as per video as below,

#include <BitsAndDroidsFlightConnector.h>

BitsAndDroidsFlightConnector connector = BitsAndDroidsFlightConnector();

byte toggleALastState;
byte toggleBLastState;
const byte togglePinA = 3;
const byte togglePinB = 4;
const byte togglePinC = 5;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(togglePinA, INPUT_PULLUP);
  pinMode(togglePinB, INPUT_PULLUP);
  pinMode(togglePinC, INPUT_PULLUP);
}

void loop() {
  // put your main code here, to run repeatedly:
  byte toggleAState = digitalRead(togglePinA);
  byte toggleBState = digitalRead(togglePinB);
  if(toggleAState != toggleALastState || toggleBState != toggleBLastState ){
  if(toggleAState == LOW){

    Serial.println(connector.sendFlaps1());
    delay(200);
  } 
  
  else if(toggleBState == LOW){

    Serial.println(connector.sendFlaps3());
    delay(200);
  } 
  else if(toggleAState == HIGH && toggleBState == HIGH){
   
    Serial.println(connector.sendFlaps2());
    delay(200);
  }
  toggleALastState = toggleAState;
  toggleBLastState = toggleBState;
  }

}

When I compile I get below errors, Any help please?

C:\Users\sim_t\Desktop\bitsanddroid\new\new.ino: In function 'void loop()':
new:26:30: error: 'class BitsAndDroidsFlightConnector' has no member named 'sendFlaps1'
     Serial.println(connector.sendFlaps1());
                              ^
new:32:30: error: 'class BitsAndDroidsFlightConnector' has no member named 'sendFlaps3'
     Serial.println(connector.sendFlaps3());
                              ^
new:37:30: error: 'class BitsAndDroidsFlightConnector' has no member named 'sendFlaps2'
     Serial.println(connector.sendFlaps2());
                              ^
exit status 1
'class BitsAndDroidsFlightConnector' has no member named 'sendFlaps1'

**Comment by BitsAndDroids** [comment]
As of this version you can use connector.send(sendFlaps1) or Serial.println(sendFlaps1). Basically, you can commit all the () from the send functions.

**Comment by simtcrom** [comment]
> As of this version you can use connector.send(sendFlaps1) or Serial.println(sendFlaps1). Basically, you can commit all the () from the send functions.

Thank you @BitsAndDroids
I did connector.send(sendFlaps1); and issue got resolved.
For any one else wanting to see full code. Attaching it here,
[3pos_toggle.txt](https://github.com/BitsAndDroids/Bits-and-Droids-flight-connector/files/7490096/3pos_toggle.txt)
