### ISSUE TITLE
V0.9.7 G1000ButtonExample.ino question.

### ISSUE THREAD

**Issue by simtcrom** [BitsAndDroids/Bits-and-Droids-flight-connector#12]
I am still little confused on how to make it work with Flight Sim. Here is what I did so far.
I wired two push buttons to ESP8266 Nodemcu to pins 4 and 5 .
Compiled and Flashed G1000ButtonExample.ino from the example. No errors.
Opened Serial Monitor. When I press one button I see, 753 being printed on monitor and when pressing other button 754 being printed.
I launch flight sim and loaded cessna 172 (G1000) and set camera as cockpit view.
When I press buttons, nothing happens on monitors.
Anything I am missing?

**Comment by BitsAndDroids** [comment]
I'm diving into the code to see what is going on. I'll report back once I've got more information

**Comment by simtcrom** [comment]
> I'm diving into the code to see what is going on. I'll report back once I've got more information

Thank you very much.
I am attaching my program here.
I changed the command to sendParkingBrake as it is something common on all planes.

Is there anything else I need to do on Bitsanddroidsgui.exe ? I double clicked it and selected the com of my board and hit start under INPUT. 
But button presses are not being registered there as well.
Please help me to get this working.

![image](https://user-images.githubusercontent.com/6823535/140529756-3d793008-7b85-461f-9bb0-ab363db4e287.png)

Also attaching my Windows 10 Device Manager screen shot,

![image](https://user-images.githubusercontent.com/6823535/140530029-776cffe9-2620-4583-8b77-ef9e664323bf.png)


[G1000ButtonExample.txt](https://github.com/BitsAndDroids/Bits-and-Droids-flight-connector/files/7486809/G1000ButtonExample.txt)

**Comment by simtcrom** [comment]
I got it working. Issue was I had left Serial Monitor from Arduino IDE left open. Which caused the port to be in USE.
I closed that and stopped and started input in Bitsanddroidsgui.exe and it showed connected to game.
Now button press toggles parking brake.

**Comment by BitsAndDroids** [comment]
Ah glad to hear! What happens is that the connector keeps the connection to your board open to communicate smoothly. If you open the serial monitor it closes the connection to the connector and locking it out.

**Comment by simtcrom** [comment]
> Ah glad to hear! What happens is that the connector keeps the connection to your board open to communicate smoothly. If you open the serial monitor it closes the connection to the connector and locking it out.

Thank you @BitsAndDroids
