### ISSUE TITLE
Feature request: PARKING_BRAKE_SET - Set the parking brake on/off	

### ISSUE THREAD

**Issue by simtcrom** [BitsAndDroids/Bits-and-Droids-flight-connector#14]
Hello,

Right now, DEFINITION_PARKING_BRAKE, | 420 | int sendParkingBrake(); is supported. However it is more of a toggle command. So only a momentary switch can be used.
As per [Microsoft flight sim sdk documentation](https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimVars%2FEvent_IDs%2FAircraft_Misc_Events.htm&rhsearch=parking&rhhlterm=parking&ux=search) there is,  PARKING_BRAKE_SET | Set the parking brake on/off   as well.
If that also can be accommodated in your program, I believe we can then use non momentary on off switches (of course, I still need to learn how to send the command only once inside void loop()

**Comment by BitsAndDroids** [comment]
Spend the day making it possible to set commands. So this should be in rather soon!

**Comment by BitsAndDroids** [comment]
If you add these two lines to your events.txt file:
1 (>K:PARKING_BRAKE_SET)^0#7000$0// Parking brake on
0 (>K:PARKING_BRAKE_SET)^0#7001$0// Parking brake off

You're able to turn the parking brake on with 7000 and off with 7001
I'll add them to the file in the next release as well. This allows you to use them already.
