### ISSUE TITLE
Problem with WASM module and bug in NAV frequency.

### ISSUE THREAD

**Issue by aeroelectrolight** [BitsAndDroids/Bits-and-Droids-flight-connector#21]
Hello,
first of all, thank you for your work and making it available.
I tested your latest version with one of my projects, my radio module. 
I changed the typing of the frequency-related variables from long to float and I modified the value returned in the switch function like this: activeCom1 = convertToFreq(cutValue).toFloat();
But, the NAV frequencies are badly returned by the connector.
The digits after the decimal point are missing. In a sniffer terminal, the value is returned like this: 911 112 or it should be of the form 911 112010 for example. 
The problem exists on all NAV frequencies. COM frequencies work fine. 

Second question, how should the value of the transponder be sent?
I overloaded the Send function to return a String value:
void BitsAndDroidsFlightConnector::send(int command,String value) {
    Serial. println(command + value);
}
Currently I'm converting the value to BCD format because it looks like the simconnect DLL expects it in that form. But it doesn't work! How should the value be returned to the connector?

I also wanted to use the WASM module to have access to basic variables such as: the avionic master switch but after having followed your videos and tutorials, it does not work in input or output for me.
Here is the only line I kept in the events file to perform the tests:
(A:AVIONICS MASTER SWITCH,Bool)^3b#6010$0//Avionic master switch
No value return in the sniffer terminal. I don't understand the problem?

Thank you very much for your work
Best regards

**Comment by BitsAndDroids** [comment]
Somewhere during the build, the outputs.json file reverted back to an old version. I've reuploaded the files with the proper version. This should fix the nav frequencies part. 
The command and value should be separated by a space (" "). In theory, it should work with the literal values so 1478 would come in like 1478.

**Comment by BitsAndDroids** [comment]
I'll test that WASM command after work!

**Comment by BitsAndDroids** [comment]
Sorry this was left open. This is fixed in a recent release. There is a chance you'll have to remove and re-add the output for it to work.
