### ISSUE TITLE
Swaping frequencies 

### ISSUE THREAD

**Issue by lucasdelgado2022** [BitsAndDroids/Bits-and-Droids-flight-connector#53]
I'm trying to build a nav radio stack with an arduino uno, an encoder and two max7219 8digit on cascade. I manage to get the active and standby frequencies showed on the display, but if i swap them on the sim, only the active gets updated and standby only gets updated if I change the frequency. Also, the sim is not detecting the inputs from the encoder nor push buttons

**Comment by BitsAndDroids** [comment]
Hi lucas,

My apologies for the late response. I had to take some time off to attend other matters.
I’ve received several reports regarding the standby coms. I’m planning to wrap up the next update by tomorrow that will contain a fix for this.

 

Kind regards,

Dave





 <https://www.bitsanddroids.com/> https://www.bitsanddroids.com

@: ***@***.***

KVK: 84976969

 

Van: lucasdelgado2022 ***@***.***> 
Verzonden: dinsdag 2 augustus 2022 23:34
Aan: BitsAndDroids/Bits-and-Droids-flight-connector ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [BitsAndDroids/Bits-and-Droids-flight-connector] Swaping frequencies (Issue #53)

 

I'm trying to build a nav radio stack with an arduino uno, an encoder and two max7219 8digit on cascade. I manage to get the active and standby frequencies showed on the display, but if i swap them on the sim, only the active gets updated and standby only gets updated if I change the frequency. Also, the sim is not detecting the inputs from the encoder nor push buttons

**Comment by BitsAndDroids** [comment]
Hi Lucas, I've just released an update that addresses this issue. Thanks for the report!

**Comment by lucasdelgado2022** [comment]
Thank you very much Dave
